/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class AppTest {

    @Test
    fun testAppHasAGreeting() {
        assertThat(App().greeting)
            .describedAs("app should have a greeting")
            .isNotNull()
    }
}
