/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel

import java.awt.EventQueue
import javax.swing.*

class AppFrame(val appTitle: String) : JFrame() {

    init {
        createUI()
    }

    private fun createUI() {
        setTitle(appTitle)

        defaultCloseOperation = EXIT_ON_CLOSE
        setSize(300, 200)
        setLocationRelativeTo(null)
    }

}

fun main(args: Array<String>) {
    EventQueue.invokeLater {
        val appFrame = AppFrame("Kotlin Minesweep")
        appFrame.isVisible = true
    }
}
